name: SimplyTheBest CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - ".github/ISSUE_TEMPLATE/**"
      - ".github/FUNDING.yml"
      - ".editorconfig"
      - "fastlane/**"
      - "CONTRIBUTING.md"
      - "LICENSE"
      - "README.md"
      - "ROADMAP.md"
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Setup CMake and Ninja
        uses: lukka/get-cmake@v3.20.1
      - name: Build with Gradle
        run: ./gradlew clean && ./gradlew assembleDebug
      - uses: actions/upload-artifact@v2
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
