name: card-gh-profile

on:
  schedule:
    - cron: "0 0 * * *"   #! exec every 24h
  workflow_dispatch:
  #push: {branches: ["main"]}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Get Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Configure pip cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/myusercard/cache/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-
      - name: Install dependencies
        run: python -m pip install -r myusercard/cache/requirements.txt
      - name: Update README file
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          USER_NAME: ${{ secrets.USER_NAME }}
        run: python myusercard/card.py
      - name: Commit
        run: |-
          git add .
          git diff
          git config --global user.email "github-actions-bot@juliocj7.github.io"
          git config --global user.name "JulioCj7/GitHub-Actions-Bot"
          git commit -m "Update README.md" -a || echo "No changes to commit"
          git push
