name: Snake

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # snake animation
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: Juliocj7
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
