name: snake-gh-profile

on:
  schedule:
    - cron: "* */12 * * *"   #! exec every 12h
  workflow_dispatch:
  push: {branches: ["main"]}

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: generate github-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake-light.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/github-snake-best.svg?color_snake=#c64dff&color_dots=#161b22,#1e291f,#244a26,#4da151,#52fa5a
      - name: push github-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
