name: snake

on:
  schedule:
    - cron: "* */12 * * *"   #! exec every 12h
  push: {branches: ["main"]}
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: generate github-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake-light.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/github-snake-best.svg?color_snake=#52fa5a&color_dots=#e5c9f2,#d8a0f2,#ce86f0,#cc73f5,#c64dff
      - name: push github-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
